Classement-des-Associations/le-classement.fr

public/humans.txt

chore: update human.txt file

---

assets/css/tailwind.css
tailwind.config.js

feat: update scrollbar style

---

content/le-pense-bete.md

fix: update links tree

---

content/le-pense-bete.md

fix: pense bete

---

content/le-pense-bete.md

feat: add links for brochures

---

content/le-pense-bete.md

feat: add faq in links

---

nuxt.config.ts

fix: default locale content

---

content/0.index.md
content/8.faq.md
content/le-pense-bete.md
server/routes/sitemap.xml.ts

fix: sitemap

---

composables/useGradient.ts

feat: add gradient composable

---

content/design-kit.md

fix: design kit title

---

content/5.blog/clap-de-fin-2022.md

fix: typo in article

---

content/5.blog/clap-de-fin-2022.md

fix: clap de fin futur président

---

content/5.blog/clap-de-fin-2022.md

fix: typo blog

---

content/7.press-kit.md

fix: title press kit

---

assets/css/tailwind.css

fix: header font

---

content/le-pense-bete.md

fix: title in le-pense-bete

---

components/TheFooter.vue

fix: remove bnei and bnem in footer

---

app.vue
nuxt.config.ts
package.json
yarn.lock

feat: add robots

---

assets/css/tailwind.css
tailwind.config.js

fix: fonts

---

nuxt.config.ts

fix: add settings for prerendering mode

---

app.vue
content/0.index.md
content/1.le-concours.md
content/10.le-reglement.md
content/11.cgu.md
content/2.le-palmares.md
content/4.devenir-partenaire.md
content/5.blog/clap-de-fin-2022.md
content/5.blog/index.md
content/6.a-propos.md
content/7.press-kit.md
content/8.nous-contacter.md
content/9.faq.md
content/design-kit.md
content/le-pense-bete.md
nuxt.config.ts

fix: social images

---

app.vue
nuxt.config.ts

refactor: head

---

public/humans.txt

fix: update humans.txt

---

.gitignore
app.vue
content/0.index.md
content/1.le-concours.md
content/4.devenir-partenaire.md
nuxt.config.ts
package.json
yarn.lock

refactor: use seo kit

---

components/TheFooter.vue
components/TheHeader.vue
components/base/BaseSection.vue

fix: header and footer section

---

components/content/blog/BlogCard.vue
composables/useGradient.ts
content/2.le-palmares.md
content/4.devenir-partenaire.md
content/5.blog/.template.md
tailwind.config.js
types/gradient.ts

fix: gradients

---

components/content/blog/BlogCardList.vue

fix: order articles blog

---

nuxt.config.ts
package.json
yarn.lock

refactor: remove unlighthouse

---

content/2.le-palmares.md

fix: supbiodance school

---

content/2.le-palmares.md

fix: typo in plamares

---

package.json
yarn.lock

chore: remove dependencies sitemap

---

content/0.index.md

fix: remove bnei and bnem from home

---

components/blog/BlogMobileToc.vue
layouts/article.vue

fix: extract mobile to to a component

---

components/content/blog/BlogListItem.vue
components/content/press/PressList.vue
components/content/press/PressListItem.vue
composables/date.ts
layouts/article.vue

feat: use date composables

---

content/design-kit.md

fix: design kit colors

---

content/le-pense-bete.md

fix: remove brochures

---

components/classement/ClassementLink.vue
components/content/DocumentDrivenNotFound.vue
package.json
tailwind.config.js
yarn.lock

feat: create not found component

---

.github/workflows/semantic-pull-request.yml

ci: add semantic pr action

---

components/blog/BlogCard.vue
layouts/article.vue

fix: blog margin

---

assets/css/tailwind.css
components/TheFooter.vue
components/TheHeader.vue
components/content/design-kit/DesignKitColorCard.vue
components/content/design-kit/DesignKitLogoCard.vue
yarn.lock

fix: design kit download links

---

app.vue
components/TheHeader.vue
components/content/blog/BlogList.vue
components/content/blog/BlogSection.vue
components/content/hero/Hero.vue
composables/useBlog.ts
content/5.blog/index.md
nuxt.config.ts

feat: add page transition

---

content/4.partenaires/0.index.md

fix: typo in partenaires page

---

public/_redirects

chore: add redirect

---

components/content/partners/PartnersBecomeSection.vue

fix: partenaires button

---

components/TheHeader.vue
components/blog/BlogCard.vue
components/content/CenteredLink.vue
components/content/classement/ClassementLink.vue
components/content/tour-asso/TourAssoRegistrationLink.vue
content/9.faq.md
content/classement/1.concours.md
layouts/article.vue
tailwind.config.js

fix: many buttons styles

---

components/base/BaseNuxtLink.vue
components/content/dump-thinker/DumpThinkerLastArticles.vue

fix: le pense bete

---

components/TheMobileNavigation.vue

fix: mobile navigation

---

assets/css/tailwind.css
components/blog/BlogCard.vue
components/home/HomeItem.vue

fix: remove apply

---

content/9.faq.md

fix: faq button

---

app.config.ts
components/TheFooter.vue
components/content/classement/ClassementNewsletterLink.vue
content/11.cgu.md

feat: add newsletter

---

components/TheFooter.vue
components/blog/BlogCard.vue
components/content/blog/BlogSection.vue
components/content/newsletter/Newsletter.vue
components/content/newsletter/NewsletterLink.vue
components/content/newsletter/NewsletterSection.vue
content/0.index.md
content/5.blog/index.md
content/newsletter/merci.md
layouts/article.vue
nuxt.config.ts

fix: newsletter

---

content/newsletter/index.md
nuxt.config.ts

feat: add newsletter page

---

app.config.ts
components/content/CenteredLink.vue
components/content/battle/BattleLink.vue
content/classement/1.battle.md
content/le-pense-bete.md

fix: battle link

---

.gitignore
scripts/fetch-associations/index.mjs

fix: participations concours

---

components/content/home/HomeTrophy.vue

Voici une petite restructuration du code, plus optimisé avec une fonction render, une d'init, etc.
Un ``cancelAnimationFrame(AnimationID)`` au niveau du hook d'unmounted pour arrêter l'animation, et une animation en fonction d'une clock et pas d'une valeur fixe !
Voilà voilà, j'ai rajouté des lumières tout autour, comme ça on voit mieux le texte.
C'est cadeau

refactor: :art: Three js optimisation and lights
